//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhostRider.Zaba.Bll
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFeatures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductFeatures()
        {
            this.ProductFeaturesMap = new HashSet<ProductFeaturesMap>();
        }
    
        public int Id { get; set; }
        public string FeatureName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductFeaturesMap> ProductFeaturesMap { get; set; }
    }
}
