//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhostRider.Zaba.Bll
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFeaturesValue
    {
        public int Id { get; set; }
        public Nullable<int> ProductFeaturesMapId { get; set; }
        public string Value { get; set; }
    
        public virtual ProductFeaturesMap ProductFeaturesMap { get; set; }
    }
}
